import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, blog, huntingcoder" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.myImg}
            src="/Home.jpg"
            width={256}
            height={171}
          />
          <h1>&lt; Hunting Coder /&gt;</h1>

          <div className={styles.blogs}>
            <h2>Latest Blogs</h2>
            <div className={styles.blogItem}>
              <h3>How to Learn JavaScript In 2026</h3>
              <p>
                JavaScript is the language used to design logic for the web
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Est
                ipsa dolore amet!
              </p>
              <button className={styles.btn}>Read More</button>
            </div>
            <div className={styles.blogItem}>
              <h3>How to Learn JavaScript In 2026</h3>
              <p>
                JavaScript is the language used to design logic for the web
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Est
                ipsa dolore amet!
              </p>
              <button className={styles.btn}>Read More</button>
            </div>
            <div className={styles.blogItem}>
              <h3>How to Learn JavaScript In 2026</h3>
              <p>
                JavaScript is the language used to design logic for the web
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Est
                ipsa dolore amet!
              </p>
              <button className={styles.btn}>Read More</button>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
