import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
     <style jsx>
      {
        `h2{
           font-size:38px;
         }
        h3{
           font-size:28px;
        }
        `
      }
     </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, blog, huntingcoder" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className={styles.intro}>
            <h1>Hunting Coder</h1>
            <Image className={styles.myImg} src="/Home.jpg" width={256} height={171}/>
            <p>
              A Looking For Hunting Coder by a hunting coder
            </p>
            <div className="blogs">
              <h2>Latest Blogs</h2>
              <div className="blogItem">
                <h3>How to Learn JavaScript In 2026</h3>
                <p>JavaScript is the language used to design logic for the web</p>
              </div>
               <div className="blogItem">
                <h3>How to Learn JavaScript In 2026</h3>
                <p>JavaScript is the language used to design logic for the web</p>
              </div>
               <div className="blogItem">
                <h3>How to Learn JavaScript In 2026</h3>
                <p>JavaScript is the language used to design logic for the web</p>
              </div>
            </div>
          </div>
    
        </main>
      </div>
    </>
  );
}
